### ISSUE TITLE
Tinap exception on windows: NotImplementedError

### ISSUE THREAD

**Issue by acreskeyMoz** [tarekziade/tinap#10]
Using tinap on Windows:
I've built it with a Python 3.6.5 virtual env, producing a tinap.exe
However when I try to run it, I get something like this:

```$ tinap --host 192.168.86.180 --port 80 --upstream-host 192.168.86.180 --upstream-port 8080
Starting Forwarder 192.168.86.180:80 => 192.168.86.180:8080
Traceback (most recent call last):
  File "c:\users\Andrew\tools\tinap\tinap\Scripts\tinap-script.py", line 11, in <module>
    load_entry_point('tinap', 'console_scripts', 'tinap')()
  File "c:\users\Andrew\tools\tinap\tinap\tinap\__init__.py", line 88, in main
    sig, lambda sig=sig: asyncio.ensure_future(shutdown(server))
  File "c:\mozilla-build\python3\Lib\asyncio\events.py", line 499, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

**Comment by tarekziade** [comment]
note to myself, on win32, intercept KeyboardInterrupt and call the handler

**Comment by tarekziade** [comment]
I make this better. it requires installing the pywin32 lib now on windows though. 
Let me know how that works for you now

```
pip install pywin32
```

**Comment by acreskeyMoz** [comment]
Even though I've install `pywin32` (and see it listed), I'm still getting the `ModuleNotFoundError: No module named 'win32api'` error).
I've tried creating new command prompt, but I see them same error.

I also tried running the post-install script, ` python Scripts/pywin32_postinstall.py -install` from an answer here:
https://stackoverflow.com/questions/21343774/importerror-no-module-named-win32api

I'm wondering if this problematic being built with python3.7 but running in 2.7?

```
C:\Users\Andrew\tools\tinap\Scripts>pip install pywin32
Requirement already satisfied: pywin32 in c:\users\andrew\tools\tinap\lib\site-packages\pywin32-227-py3.7-win-amd64.egg (227)

C:\Users\Andrew\tools\tinap\Scripts>tinap.exe
Starting Forwarder 127.0.0.1:8888 => 127.0.0.1:8080 (rtt=0, inkbps=0.0, outkbps=0.0)
You need to run 'pip install pywin32'
Traceback (most recent call last):
  File "C:\Users\Andrew\tools\tinap\Scripts\tinap-script.py", line 11, in <module>
    load_entry_point('tinap', 'console_scripts', 'tinap')()
  File "c:\users\andrew\tools\tinap\tinap\tinap\__init__.py", line 110, in main
    import win32api
ModuleNotFoundError: No module named 'win32api'

C:\Users\Andrew\tools\tinap\Scripts>pip list
Package    Version Location
---------- ------- ---------------------------------
pip        19.3.1
pypiwin32  223
pywin32    227
setuptools 41.6.0
tinap      0.1     c:\users\andrew\tools\tinap\tinap
wheel      0.33.6
```
